import type { ReactNode } from "react";
import {
  DashboardOutlined,
  UnorderedListOutlined,
  FileAddOutlined,
  AppstoreAddOutlined,
  UserOutlined,
  SettingOutlined,
  ApartmentOutlined,
  BranchesOutlined,
  TeamOutlined,
  MessageOutlined,
  AuditOutlined,
  SafetyOutlined,
  KeyOutlined,
  MenuOutlined,
  HistoryOutlined,
  BankOutlined,
} from "@ant-design/icons";

export const iconMap: Record<string, ReactNode> = {
  DashboardOutlined: <DashboardOutlined />,
  UnorderedListOutlined: <UnorderedListOutlined />,
  FileAddOutlined: <FileAddOutlined />,
  AppstoreAddOutlined: <AppstoreAddOutlined />,
  UserOutlined: <UserOutlined />,
  SettingOutlined: <SettingOutlined />,
  ApartmentOutlined: <ApartmentOutlined />,
  BranchesOutlined: <BranchesOutlined />,
  TeamOutlined: <TeamOutlined />,
  MessageOutlined: <MessageOutlined />,
  AuditOutlined: <AuditOutlined />,
  SafetyOutlined: <SafetyOutlined />,
  KeyOutlined: <KeyOutlined />,
  MenuOutlined: <MenuOutlined />,
  HistoryOutlined: <HistoryOutlined />,
  BankOutlined: <BankOutlined />,
};
